stages:
  - package_base
  - package_mid
  - package_final
  - upload_to_github

variables:
  HELM_REPO_DIR: "."
  HELM_OUTPUT_DIR: "./packages"
  GITHUB_REPO: "fomsio/helm-charts"
  GITHUB_PAGES_BRANCH: "gh-pages"

# 1단계
package_base:
  stage: package_base
  script:
    - mkdir -p ${HELM_OUTPUT_DIR}
    - for chart in foms-operatorlog-ms foms-auth-ms foms-resource-ms foms-service-cnpg-ms foms-service-elasticsearch-ms foms-service-kafka-ms foms-service-mysql-ms foms-service-postgresql-ms foms-service-redis-cluster-ms foms-service-redis-ms foms-service-zookeeper-ms foms-user-ms tesseract-cube kauntlet; do
      echo "Packaging $chart";
      helm dependency update ${HELM_REPO_DIR}/$chart/charts || true;
      helm package ${HELM_REPO_DIR}/$chart/charts -d ${HELM_OUTPUT_DIR}/$chart;
      done
  artifacts:
    paths:
      - ${HELM_OUTPUT_DIR}

# 2단계
package_mid:
  stage: package_mid
  needs: [package_base]
  script:
    - helm repo add local-packages file://${CI_PROJECT_DIR}/${HELM_OUTPUT_DIR}
    - helm repo update
    - for chart in foms-api-server foms-ui; do
      echo "Packaging $chart";
      helm dependency update ${HELM_REPO_DIR}/$chart/charts;
      helm package ${HELM_REPO_DIR}/$chart/charts -d ${HELM_OUTPUT_DIR}/$chart;
      done
  artifacts:
    paths:
      - ${HELM_OUTPUT_DIR}

# 3단계
package_final:
  stage: package_final
  needs: [package_mid]
  script:
    - helm repo add local-packages file://${CI_PROJECT_DIR}/${HELM_OUTPUT_DIR}
    - helm repo update
    - for chart in foms-engine foms-platform; do
      echo "Packaging $chart";
      helm dependency update ${HELM_REPO_DIR}/$chart/charts;
      helm package ${HELM_REPO_DIR}/$chart/charts -d ${HELM_OUTPUT_DIR}/$chart;
      done
    # index.yaml 병합 생성
    - find ${HELM_OUTPUT_DIR} -name "*.tgz" -exec cp {} ${HELM_OUTPUT_DIR}/ \;
    - helm repo index ${HELM_OUTPUT_DIR}
  artifacts:
    paths:
      - ${HELM_OUTPUT_DIR}

# 4단계: GitHub Pages 업로드
upload_to_github:
  stage: upload_to_github
  needs: [package_final]
  script:
    - git config --global user.name "${GITLAB_USER_NAME:-GitLab CI}"
    - git config --global user.email "${GITLAB_USER_EMAIL:-ci@example.com}"
    - git clone --branch ${GITHUB_PAGES_BRANCH} https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git gh-pages
    - cd gh-pages
    - for dir in ${CI_PROJECT_DIR}/${HELM_OUTPUT_DIR}/*; do
      [ -d "$dir" ] || continue;
      chart=$(basename "$dir");
      mkdir -p "$chart";
      cp "$dir"/*.tgz "$chart/" || true;
      done
    - cp ${CI_PROJECT_DIR}/${HELM_OUTPUT_DIR}/index.yaml .
    - git add .
    - git commit -m "Update Helm packages on $(date -u '+%Y-%m-%d %H:%M:%S')"
    - git push origin ${GITHUB_PAGES_BRANCH}
  only:
    - tags
